version: "3.8"

services:
  linuxcode/inventory_manager:
    build: 
      context: .
      dockerfile: ./build/dockerfiles/linuxcode/inventory_manager.dockerfile
    ports:
      - "80:80"
    environment:
      TZ: Europe/Berlin
      RESPATH: /custom/res/
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 3
      # disable: false