version: '3.8'

services:
  inventory_manager:
    build:
      context: .
      dockerfile: ./build/dockerfiles/app.dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 5s
      retries: 3
      # disable: false

  db:
    container_name: app-postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${APP_DATABASE_NAME}
      POSTGRES_USER: ${APP_DATABASE_USER}
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
    ports:
      - '5432:5432'

  dbmigration:
    container_name: app-postgres-migration
    build:
      context: .
      dockerfile: ./build/dockerfiles/migrate.dockerfile
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
