---
version: 3

vars:
  DOCKER_URL: 'your-docker-url'
  DOCKER_USER: 'your-docker-user'
  DOCKER_PASS: 'your-docker-password'
  IMAGE: 'example'
  TAG: 'latest'
  CURRENT_DIR: '.'

# To run this taskfile, install taskfile using
# go install github.com/go-task/task/v3/cmd/task@latest

# To run the taskfile, use the following command
# task <task-name>

tasks:
  generate-env-file:
    desc: 'Generate the .env file'
    cmds:
      - echo "Generating the .env file"
      - cp .env.example .env

  run-local-build-docker:
    desc: 'Run the docker-compose file'
    cmds:
      - echo "Starting the linuxcode/inventory_managerlication with docker."
      - docker-compose up --build

  lint:
    desc: 'Lint the project using golangci-lint'
    cmds:
      - echo "linting the project"
      - docker run --rm -v "{{.CURRENT_DIR }}/src:/src" golangci/golangci-lint:latest /bin/sh -c "cd /src
      - golangci-lint run"

  build-push:
    desc: 'Build and push the docker image to the docker repo'
    cmds:
      - echo "Building the image and pushing to repo"
      - docker login ${DOCKER_URL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - docker build . -t ${DOCKER_URL}/${IMAGE}:${TAG}
      - docker push ${DOCKER_URL}/${IMAGE}:${TAG}
      - docker logout

  gen-sql:
    desc: 'Generate the sql files to create the database schema'
    cmds:
      - echo "Generating the sql"
      - npx -p @dbml/cli dbml2sql ./database/schema.dbml -o ./database/schema.sql

  gen-sqlc:
    desc: 'Generate the sqlc files to create the database repo'
    cmds:
      - echo "Generating the sqlc"
      - docker run --rm -v {{ .CURRENT_DIR }}/database:/src -w /src sqlc/sqlc generate
      - rm -rf ./src/pkg/repo/generated
      - mv ./database/generated ./src/pkg/repo

  lint-api:
    desc: 'Lint the api-spec using redocly'
    cmds:
      - echo "Linting the api-spec"
      - docker run --rm -v {{ .CURRENT_DIR }}/api-spec/:/spec redocly/cli lint --generate-ignore-file api.yml

  bundle-api:
    desc: 'Bundle the api-spec using redocly'
    cmds:
      - echo "Bundling the api-spec using redocly/redoc"
      - docker run --rm -v {{ .CURRENT_DIR }}/api-spec/:/spec redocly/cli bundle api.yml -o bundle.yml

  generate-api-chi:
    desc: 'Generate the api for chi server using oapi-codegen'
    cmds:
      - echo "Generating the api for chi server using oapi-codegen"
      - oapi-codegen --config ./api-spec/server.cfg.yml ./api-spec/bundle.yml > ./src/pkg/server/generated/api.gen.go

  generate-api-types:
    desc: 'Generate the types for the api using oapi-codegen'
    cmds:
      - echo "Generating the types for the api using oapi-codegen"
      - oapi-codegen -generate types -package server ./api-spec/bundle.yml > ./src/pkg/server/generated/types.gen.go

  generate-api:
    cmds:
      - task bundle-api
      - task generate-api-types
      - task generate-api-chi
    desc: 'Generate the api for the server using oapi-codegen'

  install-local-tools:
    desc: 'Install the local tools'
    cmds:
      - echo "Installing the dependencies"
      - npm install -g @dbml/cli
      - go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@latest
