/*
Sample Service

Service to handle stuff.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dto

// ErrorBadRequest struct for ErrorBadRequest
type ErrorBadRequest struct {
	Messages []string `json:"messages"`
}
