/*
Sample Service

Service to handle stuff.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dto

// ErrorInternalServerError struct for ErrorInternalServerError
type ErrorInternalServerError struct {
	// human readable description of the error.
	Msg string `json:"msg"`
	// uuid of the error that occured. Useful for tracing down the error in log output.
	Uuid string `json:"uuid"`
}
