/*
Sample Service

Service to handle stuff.

API version: 0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dto

// Version struct for Version
type Version struct {
	// Date-time the app has been compiled.
	BuildDate string `json:"buildDate"`
	// Date-time the current build commit has be committed.
	CommitDate string `json:"commitDate"`
	// hash of the current build commit.
	CommitHash string `json:"commitHash"`
	// service description.
	Description string `json:"description"`
	// service version.
	Version string `json:"version"`
}
