# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
examples/responses/ItemListResponseExample.yml:
  no-invalid-media-type-examples:
    - '#//items/1/type'
