# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
examples/responses/ItemListResponseExample.yml:
  no-invalid-media-type-examples:
    - '#//items/1/type'
examples/types/UserExample.yml:
  no-invalid-media-type-examples:
    - '#//inventories/0'
    - '#//inventories/0/inventoryMeta'
    - '#//inventories/0/items'
examples/types/InventoryExample.yml:
  no-invalid-media-type-examples:
    - '#//items/0'
    - '#//items/0/position'
    - '#//items/0/id'
    - '#//items/0/variant'
    - '#//items/0/name'
    - '#//items/0/text'
    - '#//items/0/buy_value'
    - '#//items/0/sell_value'
    - '#//items/0/weight'
    - '#//items/0/durability'
    - '#//items/0/max_stack'
    - '#//items/0/shape'
    - '#//items/0/type'
examples/requests/MoveItemRequestExample.yml:
  no-invalid-media-type-examples:
    - '#//original_position'
    - '#//new_position'
examples/requests/AddItemToInventoryRequestExample.yml:
  no-invalid-media-type-examples:
    - '#//position'
examples/types/InventoryItemExample.yml:
  no-invalid-media-type-examples:
    - '#//position'
examples/types/VersionExample.yml:
  no-invalid-media-type-examples:
    - '#//commitHash'
