---
openapi: "3.1.0"
info:
  title: Inventory Manager
  description: Inventory Manager API
  version: 1.0.0
  license:
    name: unlicensed
    url: 'www.linuxcode.net'
tags:
  inventory:
    description: Inventory operations
  info:
    description: Information operations
  item:
    description: Item operations
  user:
    description: User operations
servers:
  - url: inventory.linuxcode.net
    description: Inventory server for example
paths:
  $ref: './resources/_index.yml'
components:
  $ref: './schemas/_index.yml'
