---
openapi: "3.1.0"
info:
  title: Inventory Manager
  description: Inventory Manager API
  version: 1.0.0
  contact:
    name: LinuxCode
    email: jbensch@linuxcode.net
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
tags:
  - name: inventory
    description: Inventory operations
  - name: info
    description: Information operations
  - name: item
    description: Item operations
  - name: user
    description: User operations
servers:
  - url: /
    description: This server
paths:
  $ref: './resources/_index.yml'
