---
openapi: "3.1.0"
info:
  title: Inventory Manager
  description: Inventory Manager API
  version: 1.0.0
  license:
    name: unlicensed
    url: 'www.linuxcode.net'
tags:
  - name: inventory
    description: Inventory operations
  - name: info
    description: Information operations
  - name: item
    description: Item operations
  - name: user
    description: User operations
servers:
  - url: inventory.linuxcode.net
    description: Inventory server for example
paths:
  $ref: './resources/_index.yml'
