---
openapi: "3.1.0"
info:
  title: Inventory Manager
  description: Inventory Manager API
  version: 1.0.0
  license:
    name: unlicensed
    url: 'www.linuxcode.net'
servers:
  - url: inventory.linuxcode.net
    description: Inventory server for example
paths:
  $ref: './resources/_index.yml'
components:
  $ref: './schemas/_index.yml'
tags:
  info:
    description: General information about the API
  item:
    description: Operations about items
  user:
    description: Operations about users
  inventory:
    description: Operations about inventories
