---
get:
  tags:
    - info
  summary: Get openapi spec as json
  description: Get openapi spec as json
  operationId: getOpenAPIJSON
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            type: object
