---
get:
  tags:
    - info
  parameters:
    render:
      in: query
      description: OpenAPI html renderer
      required: false
      schema:
        type: string
      example: scalar or spotlight
  summary: Get describing html of openapi spec
  description: Get describing html of openapi spec
  operationId: getOpenAPIHTML
  responses:
    '200':
      description: OK
      content:
        text/html:
          schema:
            type: string
            example: "<html>...</html>"
