---
get:
  tags:
    - info
  parameters:
    - name: render
      in: query
      description: OpenAPI html renderer
      required: false
      schema:
        type: string
        description: OpenAPI html renderer name (scalar or spotlight)
        example: scalar
  summary: Get describing html of openapi spec
  description: Get describing html of openapi spec
  operationId: getOpenAPIHTML
  responses:
    '200':
      description: The rendered HTML for the OpenAPI spec
      content:
        text/html:
          schema:
            type: string
            example: "<html>...</html>"
