---
get:
  tags:
    - info
  summary: Get openapi spec as json
  description: Get openapi spec as json
  operationId: getOpenAPIJSON
  responses:
    '200':
      description: The OpenAPI spec as JSON
      content:
        application/json:
          schema:
            type: object
    '400':
      description: You somehow managed to mess up the request
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'

  # This API has no security
  security: []
