---
post:
  summary: Add a new item to the inventory at the first possible position
  description: Add a new item to the inventory at the first possible position
  operationId: addItemInInventory
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    required: true
    description: Item to add to inventory and quantity and optional position
    content:
      application/json:
        schema:
          $ref: '../../schemas/_index.yml#/AddItemToInventoryRequest'
  responses:
    '200':
      description: Added item to inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/InventoryItem'
    '400':
      description: Bad request (e.g. invalid item)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'

  # This API has no security
  security: []
