---
get:
  summary: Get all inventories
  operationId: getAllInventories
  tags:
    - inventory
  responses:
    '200':
      description: successful operation - returns a list of inventories
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/inventory_list_response'
    '404':
      description: No inventories found
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/error'

  # This API has no security
  security: []

post:
  summary: Add new inventory
  operationId: addInventory
  tags:
    - inventory
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/_index.yml#/inventory_post_request'
  responses:
    '201':
      description: Added inventory - returns the newly created inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/inventory'
    '400':
      description: Bad request - e.g. invalid inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/error'

  # This API has no security
  security: []
