---
get:
  summary: Get inventory by ID
  description: Get inventory by ID
  operationId: getInventoryById
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: successful operation - returns inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Inventory'
    '400':
      description: Invalid ID supplied (e.g. not an integer)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'

    '404':
      description: Can not find inventory (inventory ID)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'

  # This API has no security
  security: []

put:
  summary: Update an inventory
  description: Update an inventory
  operationId: updateInventoryById
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory that needs to be updated
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    required: true
    description: Inventory object that needs to be updated
    content:
      application/json:
        schema:
          $ref: '../../schemas/_index.yml#/InventoryPostRequest'
  responses:
    '200':
      description: Update done - returns updated inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Inventory'
    '404':
      description: Can not find inventory (inventory ID)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'
    '400':
      description: Invalid ID supplied (e.g. not an integer)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'

  # This API has no security
  security: []

delete:
  summary: Delete inventory by ID
  description: Delete inventory by ID
  operationId: deleteInventoryById
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory to delete
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: Deleted inventory (inventory ID)
    '400':
      description: Invalid ID supplied (e.g. not an integer)
    '404':
      description: Can not find inventory (inventory ID)

  # This API has no security
  security: []
