---
get:
  summary: Get all inventories
  operationId: getAllInventories
  tags:
    - inventory
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            type: array
            items: 
              $ref: '../../schemas/_index.yml#/inventory_list_response'
    '404':
      description: No inventories found

  # This API has no security
  security: []

post:
  summary: Add new inventory
  operationId: addInventory
  tags:
    - inventory
  requestBody:
    required: true
    content:
      application/json:
        schema: 
          $ref: '../../schemas/_index.yml#/inventory_post_request'
  responses:
    '201':
      description: Added inventory
      content:
        application/json:
          schema: 
            $ref: '../../schemas/_index.yml#/inventory'
    '400':
      description: Bad request

  # This API has no security
  security: []
