---
get:
  summary: Get all inventories
  description: Get all inventories
  operationId: getAllInventories
  tags:
    - inventory
  responses:
    '200':
      description: successful operation - returns a list of inventories
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/InventoryListResponse'
    '404':
      description: No inventories found
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'

  # This API has no security
  security: []

post:
  summary: Add new inventory
  description: Add new inventory
  operationId: addInventory
  tags:
    - inventory
  requestBody:
    required: true
    description: Inventory to add to the system
    content:
      application/json:
        schema:
          $ref: '../../schemas/_index.yml#/InventoryPostRequest'
  responses:
    '201':
      description: Added inventory - returns the newly created inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Inventory'
    '400':
      description: Bad request - e.g. invalid inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'

  # This API has no security
  security: []
