---
get:
  summary: Get inventory by ID
  operationId: getInventoryById
  tags:
    - inventory
  parameters:
    inventoryId:
      in: path
      description: ID of inventory
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: successful operation
      content:
        application/json:
          schema:
            items:
              $ref: '../../schemas/_index.yml#/inventory'
    '400':
      description: Invalid ID supplied
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/error'

    '404':
      description: Can not find inventory (inventory ID)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/error'

  # This API has no security
  security: []

put:
  summary: Update an inventory
  operationId: updateInventoryById
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory that needs to be updated
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../../schemas/_index.yml#/inventory_post_request'
  responses:
    '200':
      description: Update done
    '404':
      description: Can not find inventory (inventory ID)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/error'
    '400':
      description: Invalid ID supplied
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/error'

delete:
  summary: Delete inventory by ID
  operationId: deleteInventoryById
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory to delete
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: Deleted inventory (inventory ID)
    '400':
      description: Invalid ID supplied
    '404':
      description: Can not find inventory (inventory ID)

  # This API has no security
  security: []
