---
get:
  summary: Get inventory by ID
  description: Retrieve an inventory by ID
  operationId: getInventoryById
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory to return
      required: true
      schema:
        type: integer
        format: int64
      example: 1
  responses:
    '200':
      description: successful operation - returns inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Inventory'
          example:
            $ref: '../../examples/_index.yml#/InventoryExample'
    '400':
      description: Invalid ID supplied (e.g. not an integer) - can not find inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'
          example:
            $ref: '../../examples/_index.yml#/ErrorExample'
    '404':
      description: Can not find inventory (inventory ID) to return

  # This API has no security
  security: []

put:
  summary: Update an inventory
  description: Update an inventory by ID
  operationId: updateInventoryById
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory to update
      required: true
      schema:
        type: integer
        format: int64
      example: 1
  requestBody:
    required: true
    description: Inventory object that needs to be updated
    content:
      application/json:
        schema:
          $ref: '../../schemas/_index.yml#/InventoryPostRequest'
        example:
          $ref: '../../examples/_index.yml#/InventoryPostRequestExample'
  responses:
    '200':
      description: Update done - returns updated inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Inventory'
          example:
            $ref: '../../examples/_index.yml#/InventoryExample'
    '404':
      description: Can not find inventory (inventory ID) to update
    '400':
      description: Invalid ID supplied (e.g. not an integer) - can not update inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'
          example:
            $ref: '../../examples/_index.yml#/ErrorExample'

  # This API has no security
  security: []

delete:
  summary: Delete an inventory
  description: Delete an inventory by ID
  operationId: deleteInventoryById
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory to delete
      required: true
      schema:
        type: integer
        format: int64
      example: 1
  responses:
    '200':
      description: Deleted inventory (inventory ID)
    '404':
      description: Can not find inventory (inventory ID) to delete
    '400':
      description: Invalid ID supplied (e.g. not an integer) - can not delete inventory
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'
          example:
            $ref: '../../examples/_index.yml#/ErrorExample'

  # This API has no security
  security: []
