---
post:
  summary: Move an item already in the inventory
  description: Move an item already in the inventory
  operationId: moveItemInInventory
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory
      required: true
      schema:
        type: integer
        format: int64
  requestBody:
    required: true
    description: Position data and quantity to move
    content:
      application/json:
        schema:
          $ref: '../../schemas/_index.yml#/MoveItemRequest'
  responses:
    '200':
      description: Moved item in inventory
    '400':
      description: Bad request (e.g. invalid item)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'

  # This API has no security
  security: []
