---
post:
  summary: Move item in Inventory
  description: Move an item already in the inventory
  operationId: moveItemInInventory
  tags:
    - inventory
  parameters:
    - name: inventoryId
      in: path
      description: ID of inventory to move item in
      required: true
      schema:
        type: integer
        format: int64
      example: 1
  requestBody:
    required: true
    description: Position data and quantity to move
    content:
      application/json:
        schema:
          $ref: '../../schemas/_index.yml#/MoveItemRequest'
        example:
          $ref: '../../examples/_index.yml#/MoveItemRequestExample'
  responses:
    '200':
      description: Moved item in inventory
    '400':
      description: Bad request (e.g. invalid item)
      content:
        application/json:
          schema:
            $ref: '../../schemas/_index.yml#/Error'
          example:
            $ref: '../../examples/_index.yml#/ErrorExample'
    '404':
      description: Can not find inventory or item in inventory


  # This API has no security
  security: []
