enum item_type {
  consumable
  armor
  rangedWeapon
  meleeWeapon
  consumableWeapon
  quest
  resource
}

table item {
  id int [pk, increment]
  name varchar(255)
  description text
  variant varchar(255)
  buy_value int
  sell_value int
  weight int
  durability int
  max_stack int
  height int
  width int
  rawshape text
  created_at timestamp [default: `now()`]
  type item_type
}

table user {
  id int [pk, increment]
  username varchar(255)
  salt varchar(255)
  password_hash varchar(255)
  email varchar(255)
  created_at timestamp [default: `now()`]
}

table inventory {
  id int [pk, increment]
  invname varchar(255)
  user_id int [ref: > user.id]
  width int
  height int
  max_weight int
  created_at timestamp [default: `now()`]
}

table inventory_item {
  id int [pk, increment]
  inventory_id int [ref: > inventory.id]
  item_id int [ref: > item.id]
  quantity int
  position_x int
  position_y int
  rotation int
  durabilityLeft int
  created_at timestamp [default: `now()`]
}
