-- SQL dump generated using DBML (dbml-lang.org)
-- Database: PostgreSQL
-- Generated at: 2024-02-19T01:08:04.945Z

CREATE TYPE "item_type" AS ENUM (
  'consumable',
  'armor',
  'rangedWeapon',
  'meleeWeapon',
  'consumableWeapon',
  'quest',
  'resource'
);

CREATE TABLE "item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "variant" varchar(255),
  "name" varchar(255),
  "description" text,
  "buy_value" float,
  "sell_value" float,
  "max_stack" int,
  "size_v" int,
  "size_h" int,
  "rawshape" text,
  "created_at" timestamp,
  "type" item_type
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255),
  "salt" varchar(255),
  "password_hash" varchar(255),
  "email" varchar(255),
  "created_at" timestamp
);

CREATE TABLE "inventory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "size_h" int,
  "size_v" int,
  "created_at" timestamp
);

CREATE TABLE "inventory_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "inventory_id" int,
  "item_id" int,
  "quantity" int,
  "position_h" int,
  "position_v" int,
  "rotation" int,
  "created_at" timestamp
);

ALTER TABLE "inventory" ADD FOREIGN KEY ("user_id") REFERENCES "user" ("id");

ALTER TABLE "inventory_item" ADD FOREIGN KEY ("inventory_id") REFERENCES "inventory" ("id");

ALTER TABLE "inventory_item" ADD FOREIGN KEY ("item_id") REFERENCES "item" ("id");
