// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: InventoryItem.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventoryItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item           *Item     `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Position       *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Quantity       int64     `protobuf:"varint,3,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	DurabilityLeft int64     `protobuf:"varint,4,opt,name=DurabilityLeft,proto3" json:"DurabilityLeft,omitempty"`
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_InventoryItem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_InventoryItem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_InventoryItem_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryItem) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *InventoryItem) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *InventoryItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryItem) GetDurabilityLeft() int64 {
	if x != nil {
		return x.DurabilityLeft
	}
	return 0
}

var File_InventoryItem_proto protoreflect.FileDescriptor

var file_InventoryItem_proto_rawDesc = []byte{
	0x0a, 0x13, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x0a, 0x49,
	0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x0d, 0x49, 0x6e,
	0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x20, 0x0a, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x2c, 0x0a,
	0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x75, 0x72, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0e, 0x44, 0x75, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x65, 0x66, 0x74, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_InventoryItem_proto_rawDescOnce sync.Once
	file_InventoryItem_proto_rawDescData = file_InventoryItem_proto_rawDesc
)

func file_InventoryItem_proto_rawDescGZIP() []byte {
	file_InventoryItem_proto_rawDescOnce.Do(func() {
		file_InventoryItem_proto_rawDescData = protoimpl.X.CompressGZIP(file_InventoryItem_proto_rawDescData)
	})
	return file_InventoryItem_proto_rawDescData
}

var file_InventoryItem_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_InventoryItem_proto_goTypes = []interface{}{
	(*InventoryItem)(nil), // 0: domain.InventoryItem
	(*Item)(nil),          // 1: domain.Item
	(*Position)(nil),      // 2: domain.Position
}
var file_InventoryItem_proto_depIdxs = []int32{
	1, // 0: domain.InventoryItem.item:type_name -> domain.Item
	2, // 1: domain.InventoryItem.position:type_name -> domain.Position
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_InventoryItem_proto_init() }
func file_InventoryItem_proto_init() {
	if File_InventoryItem_proto != nil {
		return
	}
	file_Item_proto_init()
	file_Position_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_InventoryItem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_InventoryItem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_InventoryItem_proto_goTypes,
		DependencyIndexes: file_InventoryItem_proto_depIdxs,
		MessageInfos:      file_InventoryItem_proto_msgTypes,
	}.Build()
	File_InventoryItem_proto = out.File
	file_InventoryItem_proto_rawDesc = nil
	file_InventoryItem_proto_goTypes = nil
	file_InventoryItem_proto_depIdxs = nil
}
