// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: Item.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemMeta   *ItemMeta `protobuf:"bytes,1,opt,name=ItemMeta,proto3" json:"ItemMeta,omitempty"`
	Name       string    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Text       string    `protobuf:"bytes,3,opt,name=Text,proto3" json:"Text,omitempty"`
	Type       ItemType  `protobuf:"varint,4,opt,name=Type,proto3,enum=domain.ItemType" json:"Type,omitempty"`
	Durability int64     `protobuf:"varint,5,opt,name=Durability,proto3" json:"Durability,omitempty"`
	SellValue  int64     `protobuf:"varint,6,opt,name=SellValue,proto3" json:"SellValue,omitempty"`
	BuyValue   int64     `protobuf:"varint,7,opt,name=BuyValue,proto3" json:"BuyValue,omitempty"`
	Variant    string    `protobuf:"bytes,8,opt,name=Variant,proto3" json:"Variant,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_Item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_Item_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetItemMeta() *ItemMeta {
	if x != nil {
		return x.ItemMeta
	}
	return nil
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Item) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_ARMOR
}

func (x *Item) GetDurability() int64 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *Item) GetSellValue() int64 {
	if x != nil {
		return x.SellValue
	}
	return 0
}

func (x *Item) GetBuyValue() int64 {
	if x != nil {
		return x.BuyValue
	}
	return 0
}

func (x *Item) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

var File_Item_proto protoreflect.FileDescriptor

var file_Item_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf6, 0x01, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2c, 0x0a,
	0x08, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x74,
	0x61, 0x52, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54,
	0x65, 0x78, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x44, 0x75, 0x72,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x44,
	0x75, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x65, 0x6c,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x53, 0x65,
	0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x75, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x75, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_Item_proto_rawDescOnce sync.Once
	file_Item_proto_rawDescData = file_Item_proto_rawDesc
)

func file_Item_proto_rawDescGZIP() []byte {
	file_Item_proto_rawDescOnce.Do(func() {
		file_Item_proto_rawDescData = protoimpl.X.CompressGZIP(file_Item_proto_rawDescData)
	})
	return file_Item_proto_rawDescData
}

var file_Item_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Item_proto_goTypes = []interface{}{
	(*Item)(nil),     // 0: domain.Item
	(*ItemMeta)(nil), // 1: domain.ItemMeta
	(ItemType)(0),    // 2: domain.ItemType
}
var file_Item_proto_depIdxs = []int32{
	1, // 0: domain.Item.ItemMeta:type_name -> domain.ItemMeta
	2, // 1: domain.Item.Type:type_name -> domain.ItemType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_Item_proto_init() }
func file_Item_proto_init() {
	if File_Item_proto != nil {
		return
	}
	file_ItemType_proto_init()
	file_ItemMeta_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Item_proto_goTypes,
		DependencyIndexes: file_Item_proto_depIdxs,
		MessageInfos:      file_Item_proto_msgTypes,
	}.Build()
	File_Item_proto = out.File
	file_Item_proto_rawDesc = nil
	file_Item_proto_goTypes = nil
	file_Item_proto_depIdxs = nil
}
