// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: ItemType.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemType int32

const (
	ItemType_ARMOR             ItemType = 0
	ItemType_CONSUMABLE        ItemType = 1
	ItemType_CONSUMABLE_WEAPON ItemType = 2
	ItemType_MELEE_WEAPON      ItemType = 3
	ItemType_RANGED_WEAPON     ItemType = 4
	ItemType_QUEST_ITEM        ItemType = 5
	ItemType_RESOURCE          ItemType = 6
)

// Enum value maps for ItemType.
var (
	ItemType_name = map[int32]string{
		0: "ARMOR",
		1: "CONSUMABLE",
		2: "CONSUMABLE_WEAPON",
		3: "MELEE_WEAPON",
		4: "RANGED_WEAPON",
		5: "QUEST_ITEM",
		6: "RESOURCE",
	}
	ItemType_value = map[string]int32{
		"ARMOR":             0,
		"CONSUMABLE":        1,
		"CONSUMABLE_WEAPON": 2,
		"MELEE_WEAPON":      3,
		"RANGED_WEAPON":     4,
		"QUEST_ITEM":        5,
		"RESOURCE":          6,
	}
)

func (x ItemType) Enum() *ItemType {
	p := new(ItemType)
	*p = x
	return p
}

func (x ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_ItemType_proto_enumTypes[0].Descriptor()
}

func (ItemType) Type() protoreflect.EnumType {
	return &file_ItemType_proto_enumTypes[0]
}

func (x ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemType.Descriptor instead.
func (ItemType) EnumDescriptor() ([]byte, []int) {
	return file_ItemType_proto_rawDescGZIP(), []int{0}
}

var File_ItemType_proto protoreflect.FileDescriptor

var file_ItemType_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2a, 0x7f, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x52, 0x4d, 0x4f, 0x52, 0x10, 0x00, 0x12,
	0x0e, 0x0a, 0x0a, 0x43, 0x4f, 0x4e, 0x53, 0x55, 0x4d, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4e, 0x53, 0x55, 0x4d, 0x41, 0x42, 0x4c, 0x45, 0x5f, 0x57, 0x45,
	0x41, 0x50, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x45, 0x4c, 0x45, 0x45, 0x5f,
	0x57, 0x45, 0x41, 0x50, 0x4f, 0x4e, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x41, 0x4e, 0x47,
	0x45, 0x44, 0x5f, 0x57, 0x45, 0x41, 0x50, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x52,
	0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x06, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ItemType_proto_rawDescOnce sync.Once
	file_ItemType_proto_rawDescData = file_ItemType_proto_rawDesc
)

func file_ItemType_proto_rawDescGZIP() []byte {
	file_ItemType_proto_rawDescOnce.Do(func() {
		file_ItemType_proto_rawDescData = protoimpl.X.CompressGZIP(file_ItemType_proto_rawDescData)
	})
	return file_ItemType_proto_rawDescData
}

var file_ItemType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ItemType_proto_goTypes = []interface{}{
	(ItemType)(0), // 0: domain.ItemType
}
var file_ItemType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ItemType_proto_init() }
func file_ItemType_proto_init() {
	if File_ItemType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ItemType_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ItemType_proto_goTypes,
		DependencyIndexes: file_ItemType_proto_depIdxs,
		EnumInfos:         file_ItemType_proto_enumTypes,
	}.Build()
	File_ItemType_proto = out.File
	file_ItemType_proto_rawDesc = nil
	file_ItemType_proto_goTypes = nil
	file_ItemType_proto_depIdxs = nil
}
