// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.25.1
// source: UpdateItem.proto

package domain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateItemParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Variant    string   `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	Text       string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	BuyValue   int64    `protobuf:"varint,4,opt,name=buyValue,proto3" json:"buyValue,omitempty"`
	SellValue  int64    `protobuf:"varint,5,opt,name=sellValue,proto3" json:"sellValue,omitempty"`
	Weight     int64    `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	Durability int64    `protobuf:"varint,7,opt,name=durability,proto3" json:"durability,omitempty"`
	MaxStack   int64    `protobuf:"varint,8,opt,name=maxStack,proto3" json:"maxStack,omitempty"`
	Type       ItemType `protobuf:"varint,9,opt,name=type,proto3,enum=domain.ItemType" json:"type,omitempty"`
	Shape      *Shape   `protobuf:"bytes,10,opt,name=shape,proto3" json:"shape,omitempty"`
}

func (x *UpdateItemParams) Reset() {
	*x = UpdateItemParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UpdateItem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateItemParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemParams) ProtoMessage() {}

func (x *UpdateItemParams) ProtoReflect() protoreflect.Message {
	mi := &file_UpdateItem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemParams.ProtoReflect.Descriptor instead.
func (*UpdateItemParams) Descriptor() ([]byte, []int) {
	return file_UpdateItem_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateItemParams) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateItemParams) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *UpdateItemParams) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UpdateItemParams) GetBuyValue() int64 {
	if x != nil {
		return x.BuyValue
	}
	return 0
}

func (x *UpdateItemParams) GetSellValue() int64 {
	if x != nil {
		return x.SellValue
	}
	return 0
}

func (x *UpdateItemParams) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateItemParams) GetDurability() int64 {
	if x != nil {
		return x.Durability
	}
	return 0
}

func (x *UpdateItemParams) GetMaxStack() int64 {
	if x != nil {
		return x.MaxStack
	}
	return 0
}

func (x *UpdateItemParams) GetType() ItemType {
	if x != nil {
		return x.Type
	}
	return ItemType_ARMOR
}

func (x *UpdateItemParams) GetShape() *Shape {
	if x != nil {
		return x.Shape
	}
	return nil
}

var File_UpdateItem_proto protoreflect.FileDescriptor

var file_UpdateItem_proto_rawDesc = []byte{
	0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x0b, 0x53, 0x68, 0x61, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xad, 0x02, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x75, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x62, 0x75, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73,
	0x65, 0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x64, 0x75, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65,
	0x52, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_UpdateItem_proto_rawDescOnce sync.Once
	file_UpdateItem_proto_rawDescData = file_UpdateItem_proto_rawDesc
)

func file_UpdateItem_proto_rawDescGZIP() []byte {
	file_UpdateItem_proto_rawDescOnce.Do(func() {
		file_UpdateItem_proto_rawDescData = protoimpl.X.CompressGZIP(file_UpdateItem_proto_rawDescData)
	})
	return file_UpdateItem_proto_rawDescData
}

var file_UpdateItem_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_UpdateItem_proto_goTypes = []interface{}{
	(*UpdateItemParams)(nil), // 0: domain.UpdateItemParams
	(ItemType)(0),            // 1: domain.ItemType
	(*Shape)(nil),            // 2: domain.Shape
}
var file_UpdateItem_proto_depIdxs = []int32{
	1, // 0: domain.UpdateItemParams.type:type_name -> domain.ItemType
	2, // 1: domain.UpdateItemParams.shape:type_name -> domain.Shape
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_UpdateItem_proto_init() }
func file_UpdateItem_proto_init() {
	if File_UpdateItem_proto != nil {
		return
	}
	file_Shape_proto_init()
	file_ItemType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_UpdateItem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateItemParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UpdateItem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UpdateItem_proto_goTypes,
		DependencyIndexes: file_UpdateItem_proto_depIdxs,
		MessageInfos:      file_UpdateItem_proto_msgTypes,
	}.Build()
	File_UpdateItem_proto = out.File
	file_UpdateItem_proto_rawDesc = nil
	file_UpdateItem_proto_goTypes = nil
	file_UpdateItem_proto_depIdxs = nil
}
